module.exports.userValidation = require('./user.validation')
module.exports.userValidation = require('./station.validation')
module.exports.profileValidation = require('./profile.validation')
module.exports.historyValidation = require('./history.validation')
module.exports.ratingValidation = require('./rating.validation')
module.exports.slotValidation = require('./slotValidation')
